# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure('2') do |config|
  config.vm.box = 'opensuse/MicroOS.x86_64'
  config.vm.box_version = '16.0.0.20230210'
  config.vm.guest = :linux

  config.ssh.forward_agent = true
  config.vm.network 'forwarded_port', guest: 22, host: 2222, disabled: true
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "shell" do |s|
    s.args = `pulumi stack output identity:ssh:server_access:credentials  -s spigell/identity/vagrant -j  | jq -r .publickey`
    s.inline = <<-SHELL
      echo ${@} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provision "shell" do |hack|
    hack.inline = <<-SHELL
      touch /etc/sysconfig/network/dhcp
    SHELL
  end

  config.vm.define 'k3s-server01' do |server01|
    server01.vm.hostname = 'k3s-server01'
    server01.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
  end

  config.vm.define 'k3s-agent01' do |agent01|
    agent01.vm.hostname = 'k3s-agent01'
    agent01.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
    end
  end
end
